# ArgoCD Application: ExternalDNS
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kyeol-platform
  source:
    repoURL: https://github.com/jungbin7/kyeol-platform-gitops.git
    targetRevision: main
    path: clusters/dev/addons/external-dns
  destination:
    name: dev-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

